# Generated by Django 3.1.4 on 2022-10-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='postcode',
        ),
        migrations.CreateModel(
            name='Multibuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_items', models.IntegerField(blank=True, default=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brand', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multibuy_brand', to='store.brand')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_items', models.IntegerField(blank=True, default=8, null=True)),
                ('brand', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_brand', to='store.brand')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
