# Generated by Django 3.1.4 on 2022-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221010_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibuy',
            name='name',
            field=models.CharField(default='Multibuy', max_length=200),
        ),
    ]
