# Generated by Django 3.1.4 on 2022-10-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_multibuy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multibuy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='multibuy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='multibuy_quantity',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.DeleteModel(
            name='Multibuy',
        ),
    ]
