# Generated by Django 3.1.4 on 2022-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20221010_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multibuy_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
