# Generated by Django 3.1.4 on 2022-10-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_multibuy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='multibuy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='multibuy_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='multibuy_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='multibuy_quantity',
        ),
    ]
