# Generated by Django 3.1.4 on 2022-10-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20221025_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multibuy_price2',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.425, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='multibuy_quantity2',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
    ]
